baseurl = "https://svemagie.net/"
title = "svemagie.net"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "svemagie"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Privacy]

[Privacy.disqus]
    disable = true

[Privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false

[Author]
    name = "svemagie"
    #profile = "https://google.com/+XXX"
    email = "svemagie@chibatsu.net"
    nick = "svemagie"

[Taxonomies]
    tag = "tags"

[Params]
    intro = false
    headline = "svemagie"
    description = "personal web"
    github = "https://github.com/svemagie"
    #linkedin = "https://linkedin.com/in/XXX/"
    #gplus = "https://google.com/+XXX"
    #twitter = "https://twitter.com/XXX"
    #stackoverflow = "https://stackoverflow.com/users/XXX/YYY"
    #microblog = "https://micro.blog/XXX"
    feedurl = "https://svemagie.net/index.xml"
    webmentionEndpoint = "https://svemagie.net/webmention"
    pingbackEndpoint = "https://svemagie.net/pingback"
    #micropubEndpoint = "https://svemagie.net/webmention/micropub"
    email = "svemagie@chibatsu.net"
    opengraph = true
    shareTwitter = false
    shareFacebook = false
    shareGooglePlus = false
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

#[[menu.main]]
#    name = "Projects"
#    url = "/project/"
#    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4
